### ISSUE TITLE
How to set up Netlify hosting?

### ISSUE THREAD

**Issue by frankzhangsyd** [mleary/resume#5]
Hi Matthew, I really like the resume you made. Its so beautiful and your idea about setting up two versions of resume is awesome!!

I just have a small question, how do you set up the Netlify to host only that `vitae.html` under `yourdomain.com/vitae`?

I am confused with `build settings` in Netlify and no idea how to redirect that page later back to  `yourdomain.com/vitae`.

Thank you.

**Comment by frankzhangsyd** [comment]
Firgured it out!! I will put it here just in case anyone need this in the future.

1. Deploy on Netlify.
 Have to rename `your vitae.html` to `index.html` then Netlify can automatically deploy the single html of your vitae.

2. Set up redirect under your main domain (eg. yourdomain/vitae)

Set up a raw text named `_redirects` in your *static* folder. And put the following in that raw text file.

```
/vitae              your-single-netlify-hosting-url              200
```

 Feel free to correct me 😄

**Comment by mleary** [comment]
Hi Frank, thanks for the feedback and hope my format helps!  I actually had a hacky workaround using Netlify to host the resume on a second website and direct my main website (mattleary.com) to that second site.  It worked, but if was far from elegant.  

You solution seems like the better solution on the face of it, and I will look into that next go around.  I am the process of updating my resume right now!
